### ISSUE TITLE
code: 'ENOENT'

### ISSUE THREAD

**Issue by Gajendrasinh** [maxlabelle/filepreview#12]
{ Error: spawn unoconv ENOENT
    at exports._errnoException (util.js:1036:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn unoconv',
  path: 'unoconv',
  spawnargs:
   [ '-e',
     'PageRange=1',
     '-o',
     'C:\\Users\\SYNC02~1\\AppData\\Local\\Temp\\148f8ccb4833afc1757920ede3855390d8ca0b6c1571940951980dc186a65f509fa98432f
cafb9a902ffdaf4f50b9560808f6994d4842e7a5f4b19d6bd04e7a1.pdf',
     'uploads/file-1498122478654.docx' ],
  cmd: 'unoconv -e PageRange=1 -o C:\\Users\\SYNC02~1\\AppData\\Local\\Temp\\148f8ccb4833afc1757920ede3855390d8ca0b6c15719
40951980dc186a65f509fa98432fcafb9a902ffdaf4f50b9560808f6994d4842e7a5f4b19d6bd04e7a1.pdf uploads/file-1498122478654.docx' }

how can i resolve this error

**Comment by vlaad360** [comment]
ENOENT ~ No such file or directory, take a look about you file path

**Comment by maxlabelle** [comment]
filepreview depends on 'unoconv':

  $ apt-get install unoconv

**Comment by maxlabelle** [comment]
also, in some case, if unoconv is installed but is not in the PATH environment variable, nodejs will unable to locate the executable, adjust accordingly
