### ISSUE TITLE
Its working fine on my local server but when I'm trying to convert image on linode server its not working

### ISSUE THREAD

**Issue by himanshuteotia** [maxlabelle/filepreview#13]

**Comment by maxlabelle** [comment]
can you give me more details? If there are exceptions or any output from the script, please paste it as well

**Comment by himanshuteotia** [comment]
what I'm doing here first write the file in my project upload folder then create thumbnail of that particular file at last unlink the previously write file. 

fs.writeFileSync('uploads/' + abc.jpg, binaryData, 'binary')
            var options = {
                width: 150,
                height: 150
            }
            var url =  __dirname;
            url = url.substring(0, url.indexOf("myproject")) // this my project folder name
            if (!filepreview.generateSync(url + "myproject/uploads/" + abc.jpg, url + "myproject/uploads/" + "th" + "-" + abc.jpg, options)) {
                console.log('Oops, something went wrong.');
            } else {
                console.log('File psave successfully');
            };
            fs.unlinkSync('uploads/' +abc.jpg);

**Comment by maxlabelle** [comment]
from what I understand, abc.jpg is a string and should be quoted, instead of:

```javascript
'uploads/' + abc.jpg
```

can you replace those occurrences in your code by:

```javascript
'uploads/' + 'abc.jpg'
```

**Comment by himanshuteotia** [comment]
Ahh! Sorry I was forget to put the filename in quotes when I was giving this code to you actually I changed this code a bit, which you can understand what exactly I am trying to do.

By the way what do you mean by "Include the output" ?

**Comment by himanshuteotia** [comment]
What is this line really doing?
child_process.execFileSync('convert', convertOtherArgs);
