### ISSUE TITLE
Question: How can we get this running in Angular JS, such as your demo?

### ISSUE THREAD

**Issue by ryanhinton** [maxlabelle/filepreview#15]
Hello,

Thank you for this great package.  I am attempting to figure out how I can utilize this on Angular on the client side and I am not using Node.js as a server.  I noticed you made this package work in Angular in your demo.  Are there instructions or examples on how we could make this work in Angular?

Thank you for your time!
Ryan

**Comment by maxlabelle** [comment]
The demo application in the video uses Angular but the application's back end is node.js. In the demo, the file is uploaded to the back end and the preview is generated there.

It is not possible to run this package within Angular without nodejs unless you use something like nwjs.
