### ISSUE TITLE
issues in my program

### ISSUE THREAD

**Issue by scorpionCoder** [maxlabelle/filepreview#16]
Hi, I am trying to use filepreview npm for my program below is the code.

```
var filepreview = require('filepreview');
 
  filepreview.generate('/home/myfile.docx', '/home/myfile_preview.gif', function(error) {
    if (error) {
      return console.log(error);
    }
    console.log('File preview is /home/myfile_preview.gif');
  });
```

I get the following error:

Error: spawn unoconv ENOENT
    at exports._errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:359:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn unoconv',
  path: 'unoconv',
  spawnargs:
   [ '-e',
     'PageRange=1',
     '-o',
     'C:\\Users\\Gokul\\AppData\\Local\\Temp\\ab01bc68922be403ff224ea693570b2f24eb6f0529d524b9edfdd17da5c19b469aca8bbd67b09b46ee58113734494c5659e14eb4b9b652fb8f00fc4ded442442.pdf',
     './uploads/contractUpload/scorp/Nodejs_Structure.txt' ],
  cmd: 'unoconv -e PageRange=1 -o C:\\Users\\Gokul\\AppData\\Local\\Temp\\ab01bc68922be403ff224ea693570b2f24eb6f0529d524b9edfdd17da5c19b469aca8bbd67b09b46ee58113734494c5659e14eb4b9b652fb8f00fc4ded442442.pdf ./uploads/contractUpload/scorp/Nodejs_Structure.txt' }
Error: null
Doc: { result: { ok: 1, n: 1 },
  ops:
   [ { hash: '067fee740b14efb96f4b841a3c423fe8',
       filename: 'com.eclipsesource.jshint.ui.prefs',
       _id: 59a8ed9c4c382723c4ecda8f } ],
  insertedCount: 1,
  insertedIds: [ 59a8ed9c4c382723c4ecda8f ]

I believe it is because I have not installed unoconv. Right now I have downloaded and saved LibreOffice 5 to "C:\Program Files (x86)\LibreOffice 5" and downloaded latest unoconv zip extracted it to "C:\Program Files (x86)\unoconv-0.7"

Now I don't know how to set environment variables and how to install unoconv. **Please help me. I am stuck here.**

**Comment by maxlabelle** [comment]
filepreview is only supported on linux systems.
