### ISSUE TITLE
multiple file preview

### ISSUE THREAD

**Issue by monasingh27294** [maxlabelle/filepreview#18]
hey,
can i make multiple file preview of pdf, ppt?
file preview creates preview of only first page I want preview of all pages

is there any way to do in this module?

**Comment by itsmenirajpaudel** [comment]
I am also stuck here. Did you find the solution @monasingh27294 ?

**Comment by monasingh27294** [comment]
no

**Comment by maxlabelle** [comment]
done, will be ready today in npm
