### ISSUE TITLE
Can you add width and height for preview API?

### ISSUE THREAD

**Issue by testtshoretel** [maxlabelle/filepreview#3]
Can you add width and height for preview API?

**Comment by testtshoretel** [comment]
@jolks @maxlabelle Can you add width and height for preview API?

**Comment by jolks** [comment]
Hi @testtshoretel, I can work on this after PR https://github.com/maxlabelle/filepreview/pull/4 is merged.

**Comment by maxlabelle** [comment]
@jolks sure, if you want to create another PR, i'll review & merge it

**Comment by testtshoretel** [comment]
@jolks Thanks for adding the width and height options. One more question: in one of my use cases, I do not want to save any files. All input and output are streams(buffers). Is it possible to add one more API for streams with file extensions specified in options? Thanks.
