### ISSUE TITLE
Appears to be vulnerable to arbitrary code execution

### ISSUE THREAD

**Issue by popey456963** [maxlabelle/filepreview#33]
Any chance I could message you on a private channel to describe it?  Don't entirely want to post it on a public issue.

**Comment by maxlabelle** [comment]
sure thing, email me at maxime.labelle@owasp.org

**Comment by popey456963** [comment]
Nevermind, apologies.  It was a vulnerability in `ffmpeg` that had already been discovered and fixed,  just was using an out of date version.

Thanks for making this package, it has been really useful.
