### ISSUE TITLE
What works without installing the listed apt-get? 

### ISSUE THREAD

**Issue by desduvauchelle** [maxlabelle/filepreview#7]
Hello.

I'm coding my first Electron app. 
Would love to generate file previews for different formats and so you're library looks perfect, Thanks! 

Question, I don't think I can run apt-get when the user installs the app. Do any of the previews work without the apt-get? Do you know of a solution? 

Thanks.

**Comment by maxlabelle** [comment]
Unfortunately, filepreview requires its dependencies in order to work. There is no workaround this requirement.

Note that it is very common for an application to have dependencies under Linux, this should not be a problem in most cases.
