### ISSUE TITLE
Support remote URLs

### ISSUE THREAD

**Issue by christophermina** [maxlabelle/filepreview#8]
Does this package currentlys upport remote URLs?  For instance, I'd like my file uploading service to stream files out to AWS S3 upon upload, and then with post-processing, generate file previews off the signed URL out to AWS for that resource.  This would prevent from having to manually download the file in app code, store to a temporary file directory, and extract it to the library.  Would also make it a bit easier to host this on it's own server / service, as the memory load could be higher than the normal web app, if generating previews for large files. 

I'm currently using filepreviews.io and looking for a self-hosted alternative.  

Thanks!

Chris

**Comment by maxlabelle** [comment]
No, it does not support remote urls right now, but I like the idea and I see your point.

I will add this feature soon, hopefully I will have time to do it today.

I will let you know when it's done

**Comment by maxlabelle** [comment]
done

**Comment by mbarwick83** [comment]
Is this change committed to master?

**Comment by maxlabelle** [comment]
yup
